### ISSUE TITLE
SVT VP9 ffmpeg plugin support

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#387]
SVT VP9 ffmpeg plugin is already in SVT VP9 master repo, waiting for it is tagged.

**Comment by mash-graz** [comment]
i would be really happy, if a ready made docker image would be available, that already includes your vp9 ffmpeg plugin.

are there anywhere at least some nightly builds accessible, which provide this feature?

**Comment by tianjunwork** [comment]
Hi @mash-graz svt-vp9 ffmpeg plugin is removed from docker image because it had playback issue with some file containers that not resolved at that time. Since now they are fixed, we can re-enable svt-vp9 ffmpeg plugin.
I can add a new tag for SVT-HEVC.
@jhou5 may help re-enable svt-vp9 ffmpeg plugin in this project.

**Comment by mash-graz** [comment]
i would be very happy, if we could find a way to solve this issue, because it's a really troublesome challenge to workaround all the possible pitfalls while figuring out a working Dockerfile with all three SVT ffmpeg plugins.

i just wrote an DASH/HLS encoder application during the last weeks, which i would really like to use/test with your docker image, therefore i would appreciate any help solving this issue.

**Comment by wannamit** [comment]
I was working on encoding to multiple codecs within the same docker container, namely AVC, HEVC &VP9 using FFmpeg. AVC and HEVC work fine but VP9 fails `Unknown encoder libsvt_vp9`. I tried to build a new docker image with HEVC and VP9 plugin but that too fails (VP9 plugin add fails).
In this issue, https://github.com/OpenVisualCloud/SVT-VP9/issues/97, @mash-graz has posted a Dockerfile, which I haven't tested (Will update if I test it.). But it would great if VP9 was available by default in ffmpeg-media docker image.

**Comment by xwu2git** [comment]
Please try the v20.4 branch. SVT-VP9 is enabled. 
v20.4 will be merged back to master soon.

**Comment by l1yulong** [comment]
Now OVC use SVT-VP9 official tag 0.3.0.
