### ISSUE TITLE
Feature Request for SVT (apps) only images.

### ISSUE THREAD

**Issue by xwu2git** [OpenVisualCloud/Dockerfiles#96]
that include all SVT codecs.

**Comment by dpatel257** [comment]
Are we targetting all platforms (Xeon/XeonE3/VCA2) x All OSes ?

**Comment by 1480c1** [comment]
Although a bit off topic, In my opinion, I feel that the whole targeting multiple os version thing is a bit unnecessary if the intention is to provide a container to ease video production. Unless the point of producing the same tools using different images is to prove their compatibility, I think it would be better to focus more on producing the images for a version of centos(7.6 for example) and a version of Ubuntu(18.04 for example) and try to focus more on specializing the containers

**Comment by 1480c1** [comment]
I will post a full reason in a little

**Comment by jhou5** [comment]
SVT is CPU based, In my opinion, Xeon is enough

**Comment by 1480c1** [comment]
The reason why I say that it would be better to focus less on generating images for multiple OS versions is because when it comes to the end user, it would be hard to pick and choose an appropriate tag. For example, let's say that I want to use an ffmpeg image that comes with audio stuff, aom, vpx, svt, x265, etc, I would have a hard time deciding between centos 7.4,5,6, ubuntu 16.04, 18.04, with the final decision coming down to which do I see first. This should not generally be a problem if the intention is to run ffmpeg, especially since the images are meant to run ffmpeg, which is also a bit concerning since none of the docker files have a `CMD` or `EXEC` command in them for the default program to run.

Meaning that if I do `docker run -it OpenVisualCloud/dockerfiles:xeoncentos76ffmpeg` I would need to specify `ffmpeg -i stdin ... -` after the image name

**Comment by xwu2git** [comment]
The images are created for different purposes. In general, images such as FFMPEG are designed for people to build their apps. Rarely the purpose is to run FFMPEG alone. For example, in AD-Insertion, we use the FFMPEG dockerfile as the base image and build nginx and tornadio on top. FFMPEG is just one of the many applications we use. Thus setting up CMD is not needed.

Specifically for the SVT only image, the goal is to try out the SVT apps. I agree that a single OS should be sufficient. There is not much difference when the goal is to "run" the SVT apps.

**Comment by xwu2git** [comment]
Maybe in addition to the software stack images, the development images, the service images, we need to add a showcase-images section?

**Comment by dpatel257** [comment]
The power of template based design we have implemented here allows us to develop for multiple OSes within a second. That doesn't hurt.
Adding showcase-images section would just add an extra section to README making it difficult to interpret. We should contribute to Software stack images.

**Comment by dpatel257** [comment]
Now that we have 'Software Stack Images', 'Dev Images', 'Service Images'. This can be put under 'Software stack images' under 'media'. PR #142 in progress
